export const dashboardKPIs = [
  { label: 'Total Leads', value: '2,847', change: '+12.5%', trend: 'up' as const, icon: 'Users' },
  { label: 'Active Deals', value: '$482K', change: '+8.2%', trend: 'up' as const, icon: 'DollarSign' },
  { label: 'Conversion Rate', value: '24.8%', change: '+3.1%', trend: 'up' as const, icon: 'TrendingUp' },
  { label: 'Active Projects', value: '34', change: '+5', trend: 'up' as const, icon: 'FolderOpen' },
  { label: 'AI Tasks Done', value: '1,293', change: '+18.7%', trend: 'up' as const, icon: 'Bot' },
  { label: 'Revenue MTD', value: '$128K', change: '+22.4%', trend: 'up' as const, icon: 'BarChart3' },
]

export const pipelineStages = [
  { id: 'new', name: 'New Leads', color: '#3b82f6', count: 45 },
  { id: 'contacted', name: 'Contacted', color: '#8b5cf6', count: 32 },
  { id: 'qualified', name: 'Qualified', color: '#f59e0b', count: 28 },
  { id: 'proposal', name: 'Proposal', color: '#10b981', count: 19 },
  { id: 'negotiation', name: 'Negotiation', color: '#ef4444', count: 14 },
  { id: 'won', name: 'Won', color: '#22c55e', count: 11 },
]

export const leadsData = [
  { id: '1', name: 'Sarah Mitchell', email: 'sarah@techcorp.io', company: 'TechCorp', title: 'VP Marketing', status: 'qualified', score: 87, source: 'LinkedIn', industry: 'SaaS', value: '$24K', avatar: 'SM', phone: '+1 (415) 555-0142', location: 'San Francisco, CA', website: 'techcorp.io', companySize: '51-200', revenue: '$4.2M', createdAt: '2026-04-18', lastContact: '2 days ago', tags: ['hot-lead', 'saas', 'enterprise'] },
  { id: '2', name: 'James Rodriguez', email: 'james@innovate.co', company: 'Innovate Co', title: 'CEO', status: 'proposal', score: 92, source: 'Apollo', industry: 'Fintech', value: '$48K', avatar: 'JR', phone: '+1 (212) 555-0198', location: 'New York, NY', website: 'innovate.co', companySize: '11-50', revenue: '$8.7M', createdAt: '2026-03-22', lastContact: '1 day ago', tags: ['high-value', 'fintech', 'c-level'] },
  { id: '3', name: 'Emily Chen', email: 'emily@dataflow.ai', company: 'DataFlow AI', title: 'CTO', status: 'new', score: 65, source: 'Crunchbase', industry: 'AI/ML', value: '$36K', avatar: 'EC', phone: '+1 (650) 555-0176', location: 'Palo Alto, CA', website: 'dataflow.ai', companySize: '11-50', revenue: '$2.1M', createdAt: '2026-05-10', lastContact: 'Never', tags: ['ai-ml', 'tech'] },
  { id: '4', name: 'Michael Park', email: 'michael@growthlab.com', company: 'GrowthLab', title: 'Head of Ops', status: 'contacted', score: 74, source: 'Website', industry: 'Marketing', value: '$18K', avatar: 'MP', phone: '+1 (310) 555-0134', location: 'Los Angeles, CA', website: 'growthlab.com', companySize: '51-200', revenue: '$5.5M', createdAt: '2026-04-05', lastContact: '5 days ago', tags: ['marketing', 'ops'] },
  { id: '5', name: 'Lisa Thompson', email: 'lisa@designhub.io', company: 'DesignHub', title: 'Creative Director', status: 'negotiation', score: 89, source: 'Referral', industry: 'Design', value: '$32K', avatar: 'LT', phone: '+1 (773) 555-0167', location: 'Chicago, IL', website: 'designhub.io', companySize: '11-50', revenue: '$3.8M', createdAt: '2026-02-14', lastContact: '3 hours ago', tags: ['hot-lead', 'design', 'referral'] },
  { id: '6', name: 'David Kim', email: 'david@scaleforce.io', company: 'ScaleForce', title: 'Founder', status: 'won', score: 95, source: 'LinkedIn', industry: 'SaaS', value: '$56K', avatar: 'DK', phone: '+1 (512) 555-0189', location: 'Austin, TX', website: 'scaleforce.io', companySize: '201-500', revenue: '$12.3M', createdAt: '2026-01-08', lastContact: '1 hour ago', tags: ['won', 'enterprise', 'saas'] },
  { id: '7', name: 'Rachel Green', email: 'rachel@cloudops.co', company: 'CloudOps', title: 'VP Engineering', status: 'new', score: 58, source: 'Upwork', industry: 'Cloud', value: '$22K', avatar: 'RG', phone: '+1 (206) 555-0145', location: 'Seattle, WA', website: 'cloudops.co', companySize: '51-200', revenue: '$6.8M', createdAt: '2026-05-12', lastContact: 'Never', tags: ['cloud', 'engineering'] },
  { id: '8', name: 'Alex Turner', email: 'alex@legalwise.com', company: 'LegalWise', title: 'Managing Partner', status: 'contacted', score: 71, source: 'Apollo', industry: 'Legal', value: '$40K', avatar: 'AT', phone: '+1 (617) 555-0156', location: 'Boston, MA', website: 'legalwise.com', companySize: '11-50', revenue: '$9.1M', createdAt: '2026-04-28', lastContact: '1 week ago', tags: ['legal', 'c-level'] },
  { id: '9', name: 'Nina Patel', email: 'nina@healthfirst.io', company: 'HealthFirst', title: 'Director', status: 'qualified', score: 82, source: 'Crunchbase', industry: 'Healthcare', value: '$28K', avatar: 'NP', phone: '+1 (408) 555-0123', location: 'San Jose, CA', website: 'healthfirst.io', companySize: '201-500', revenue: '$15.7M', createdAt: '2026-03-15', lastContact: '4 days ago', tags: ['healthcare', 'qualified'] },
  { id: '10', name: 'Tom Walker', email: 'tom@realestatepro.com', company: 'RealEstatePro', title: 'Broker', status: 'proposal', score: 78, source: 'Referral', industry: 'Real Estate', value: '$20K', avatar: 'TW', phone: '+1 (305) 555-0198', location: 'Miami, FL', website: 'realestatepro.com', companySize: '11-50', revenue: '$3.2M', createdAt: '2026-04-01', lastContact: '2 days ago', tags: ['real-estate', 'referral'] },
  { id: '11', name: 'Priya Sharma', email: 'priya@neuralpath.ai', company: 'NeuralPath AI', title: 'Head of Product', status: 'new', score: 62, source: 'LinkedIn', industry: 'AI/ML', value: '$30K', avatar: 'PS', phone: '+1 (408) 555-0211', location: 'Mountain View, CA', website: 'neuralpath.ai', companySize: '11-50', revenue: '$1.8M', createdAt: '2026-05-11', lastContact: 'Never', tags: ['ai-ml', 'product'] },
  { id: '12', name: 'Marcus Johnson', email: 'marcus@finvault.com', company: 'FinVault', title: 'CFO', status: 'qualified', score: 84, source: 'Apollo', industry: 'Fintech', value: '$44K', avatar: 'MJ', phone: '+1 (646) 555-0177', location: 'New York, NY', website: 'finvault.com', companySize: '51-200', revenue: '$7.4M', createdAt: '2026-03-08', lastContact: '6 hours ago', tags: ['fintech', 'c-level', 'high-value'] },
  { id: '13', name: 'Sophie Laurent', email: 'sophie@luxbrand.co', company: 'LuxBrand', title: 'Brand Director', status: 'contacted', score: 69, source: 'Crunchbase', industry: 'Retail', value: '$26K', avatar: 'SL', phone: '+1 (323) 555-0144', location: 'Los Angeles, CA', website: 'luxbrand.co', companySize: '201-500', revenue: '$22.1M', createdAt: '2026-04-22', lastContact: '3 days ago', tags: ['retail', 'brand'] },
  { id: '14', name: 'Ryan O\'Brien', email: 'ryan@devstack.io', company: 'DevStack', title: 'VP Engineering', status: 'negotiation', score: 91, source: 'Referral', industry: 'SaaS', value: '$52K', avatar: 'RO', phone: '+1 (720) 555-0166', location: 'Denver, CO', website: 'devstack.io', companySize: '51-200', revenue: '$9.8M', createdAt: '2026-02-28', lastContact: '12 hours ago', tags: ['saas', 'hot-lead', 'enterprise'] },
  { id: '15', name: 'Aisha Mohammed', email: 'aisha@edulearn.com', company: 'EduLearn', title: 'CEO', status: 'proposal', score: 80, source: 'LinkedIn', industry: 'EdTech', value: '$38K', avatar: 'AM', phone: '+1 (202) 555-0199', location: 'Washington, DC', website: 'edulearn.com', companySize: '11-50', revenue: '$2.9M', createdAt: '2026-03-30', lastContact: '1 day ago', tags: ['edtech', 'c-level'] },
  { id: '16', name: 'Chris Yang', email: 'chris@cyberwall.io', company: 'CyberWall', title: 'CISO', status: 'new', score: 55, source: 'Crunchbase', industry: 'Cybersecurity', value: '$34K', avatar: 'CY', phone: '+1 (703) 555-0188', location: 'Arlington, VA', website: 'cyberwall.io', companySize: '51-200', revenue: '$5.1M', createdAt: '2026-05-13', lastContact: 'Never', tags: ['cybersecurity', 'security'] },
  { id: '17', name: 'Olivia Barnes', email: 'olivia@greenlogix.com', company: 'GreenLogix', title: 'COO', status: 'contacted', score: 73, source: 'Website', industry: 'Logistics', value: '$28K', avatar: 'OB', phone: '+1 (404) 555-0155', location: 'Atlanta, GA', website: 'greenlogix.com', companySize: '201-500', revenue: '$18.3M', createdAt: '2026-04-15', lastContact: '4 days ago', tags: ['logistics', 'ops'] },
  { id: '18', name: 'Kevin Zhang', email: 'kevin@quantumdata.ai', company: 'QuantumData', title: 'CTO', status: 'qualified', score: 86, source: 'Apollo', industry: 'AI/ML', value: '$42K', avatar: 'KZ', phone: '+1 (650) 555-0133', location: 'Menlo Park, CA', website: 'quantumdata.ai', companySize: '11-50', revenue: '$3.6M', createdAt: '2026-03-18', lastContact: '2 days ago', tags: ['ai-ml', 'c-level', 'tech'] },
  { id: '19', name: 'Jennifer Walsh', email: 'jennifer@mediapulse.co', company: 'MediaPulse', title: 'VP Sales', status: 'proposal', score: 76, source: 'Referral', industry: 'Media', value: '$22K', avatar: 'JW', phone: '+1 (312) 555-0177', location: 'Chicago, IL', website: 'mediapulse.co', companySize: '51-200', revenue: '$6.2M', createdAt: '2026-04-10', lastContact: '6 hours ago', tags: ['media', 'sales'] },
  { id: '20', name: 'Daniel Foster', email: 'daniel@constructpro.com', company: 'ConstructPro', title: 'President', status: 'won', score: 93, source: 'LinkedIn', industry: 'Construction', value: '$64K', avatar: 'DF', phone: '+1 (972) 555-0166', location: 'Dallas, TX', website: 'constructpro.com', companySize: '201-500', revenue: '$28.7M', createdAt: '2026-01-20', lastContact: '30 min ago', tags: ['won', 'enterprise', 'c-level'] },
]

export const leadActivities = [
  { id: 'la1', leadId: '1', type: 'email_sent', description: 'Sent personalized intro email', timestamp: '2 days ago', icon: 'Mail' },
  { id: 'la2', leadId: '1', type: 'call_scheduled', description: 'Discovery call scheduled for May 16', timestamp: '2 days ago', icon: 'Phone' },
  { id: 'la3', leadId: '1', type: 'lead_created', description: 'Lead discovered via LinkedIn', timestamp: 'Apr 18', icon: 'UserPlus' },
  { id: 'la4', leadId: '2', type: 'proposal_sent', description: 'Sent $48K proposal for AI automation', timestamp: '1 day ago', icon: 'FileText' },
  { id: 'la5', leadId: '2', type: 'email_sent', description: 'Follow-up email after demo', timestamp: '3 days ago', icon: 'Mail' },
  { id: 'la6', leadId: '2', type: 'agent_executed', description: 'Prospect Intel enriched company data', timestamp: '5 days ago', icon: 'Bot' },
  { id: 'la7', leadId: '2', type: 'lead_created', description: 'Lead imported from Apollo', timestamp: 'Mar 22', icon: 'UserPlus' },
  { id: 'la8', leadId: '3', type: 'lead_created', description: 'Lead discovered on Crunchbase', timestamp: 'May 10', icon: 'UserPlus' },
  { id: 'la9', leadId: '5', type: 'deal_won', description: 'Negotiation in progress - $32K deal', timestamp: '3 hours ago', icon: 'Trophy' },
  { id: 'la10', leadId: '5', type: 'call_scheduled', description: 'Pricing call completed', timestamp: '1 day ago', icon: 'Phone' },
  { id: 'la11', leadId: '5', type: 'email_sent', description: 'Sent case studies and ROI analysis', timestamp: '3 days ago', icon: 'Mail' },
  { id: 'la12', leadId: '5', type: 'referral', description: 'Referred by Lisa at DesignHub', timestamp: 'Feb 14', icon: 'Share2' },
  { id: 'la13', leadId: '6', type: 'deal_won', description: 'Deal closed - $56K contract signed', timestamp: '1 hour ago', icon: 'Trophy' },
  { id: 'la14', leadId: '6', type: 'payment', description: 'First invoice paid - $18K', timestamp: '3 hours ago', icon: 'CreditCard' },
  { id: 'la15', leadId: '6', type: 'proposal_sent', description: 'Final proposal approved', timestamp: '1 week ago', icon: 'FileText' },
  { id: 'la16', leadId: '6', type: 'email_sent', description: 'Contract sent for signature', timestamp: '1 week ago', icon: 'Mail' },
  { id: 'la17', leadId: '9', type: 'email_sent', description: 'Sent healthcare industry report', timestamp: '4 days ago', icon: 'Mail' },
  { id: 'la18', leadId: '9', type: 'agent_executed', description: 'Lead Scout enriched contact data', timestamp: '5 days ago', icon: 'Bot' },
  { id: 'la19', leadId: '9', type: 'lead_created', description: 'Lead discovered on Crunchbase', timestamp: 'Mar 15', icon: 'UserPlus' },
  { id: 'la20', leadId: '14', type: 'deal_won', description: 'Negotiation meeting - very interested', timestamp: '12 hours ago', icon: 'Trophy' },
  { id: 'la21', leadId: '14', type: 'call_scheduled', description: 'Technical demo completed', timestamp: '2 days ago', icon: 'Phone' },
  { id: 'la22', leadId: '20', type: 'deal_won', description: 'Deal closed - $64K enterprise contract', timestamp: '30 min ago', icon: 'Trophy' },
  { id: 'la23', leadId: '20', type: 'payment', description: 'Full payment received - $64K', timestamp: '1 hour ago', icon: 'CreditCard' },
]

export const leadNotes = [
  { id: 'ln1', leadId: '1', content: 'Very interested in AI-powered lead generation. Currently using HubSpot but looking for more automation. Budget approved for Q2.', author: 'Alex', timestamp: '2 days ago' },
  { id: 'ln2', leadId: '1', content: 'Mentioned they have a team of 5 marketers who would use the platform. Wants to schedule a demo with the team next week.', author: 'Alex', timestamp: '3 days ago' },
  { id: 'ln3', leadId: '2', content: 'Fast-growing fintech startup. CEO is the decision maker. They need proposal automation and outreach tools. High priority lead.', author: 'Alex', timestamp: '5 days ago' },
  { id: 'ln4', leadId: '2', content: 'They compared us with 3 competitors. Our AI agents and automation capabilities were the key differentiator. Moving to proposal stage.', author: 'Alex', timestamp: '1 day ago' },
  { id: 'ln5', leadId: '5', content: 'Referred by David Kim. Creative agency looking to automate client onboarding and proposal generation. Strong intent signals.', author: 'Alex', timestamp: 'Feb 14' },
  { id: 'ln6', leadId: '5', content: 'Price negotiation ongoing. They want the enterprise plan at a 15% discount. Approved a 10% discount max.', author: 'Alex', timestamp: '1 day ago' },
  { id: 'ln7', leadId: '6', content: 'Enterprise SaaS client. Signed a 12-month contract. Onboarding starts next Monday. Upsell potential for additional AI agents.', author: 'Alex', timestamp: '1 hour ago' },
  { id: 'ln8', leadId: '14', content: 'Strong technical team looking for workflow automation. VP Engineering is the champion. Need to address security concerns in next call.', author: 'Alex', timestamp: '2 days ago' },
  { id: 'ln9', leadId: '20', content: 'Large construction company looking to digitize operations. President is direct decision maker. Fast-tracked deal.', author: 'Alex', timestamp: '3 days ago' },
  { id: 'ln10', leadId: '20', content: 'Deal closed! Largest contract this quarter. They want to start with 10 AI agents and expand from there.', author: 'Alex', timestamp: '30 min ago' },
]

export const aiAgents = [
  { id: '1', name: 'Lead Scout', type: 'lead_research', status: 'active', icon: 'Search', description: 'Automatically finds qualified leads from LinkedIn, Apollo, Crunchbase, and 10+ sources', model: 'gpt-4', runCount: 1247, successRate: 94.2, lastRun: '2 min ago', capabilities: ['LinkedIn Search', 'Apollo API', 'Crunchbase', 'Web Scraping', 'Lead Scoring'] },
  { id: '2', name: 'Prospect Intel', type: 'prospect_intel', status: 'active', icon: 'Brain', description: 'Researches prospects and companies automatically analyzing pain points and signals', model: 'gpt-4', runCount: 892, successRate: 91.5, lastRun: '5 min ago', capabilities: ['Company Analysis', 'Pain Point Detection', 'Signal Tracking', 'Competitive Intel'] },
  { id: '3', name: 'Outreach Pro', type: 'outreach', status: 'active', icon: 'Send', description: 'Generates hyper-personalized outreach messages across email, LinkedIn, and SMS', model: 'gpt-4', runCount: 3412, successRate: 88.7, lastRun: '1 min ago', capabilities: ['Email Personalization', 'LinkedIn DMs', 'SMS Outreach', 'A/B Testing'] },
  { id: '4', name: 'Follow-Up Engine', type: 'followup', status: 'active', icon: 'Clock', description: 'Manages follow-ups automatically based on engagement and intent signals', model: 'gpt-4', runCount: 5621, successRate: 86.3, lastRun: '3 min ago', capabilities: ['Smart Sequences', 'Engagement Tracking', 'Timing Optimization', 'Multi-Channel'] },
  { id: '5', name: 'CRM Brain', type: 'crm', status: 'active', icon: 'Database', description: 'Tracks all leads and conversations, predicts conversion probability', model: 'gpt-4', runCount: 8934, successRate: 93.1, lastRun: '30 sec ago', capabilities: ['Pipeline Analytics', 'Conversion Prediction', 'Data Enrichment', 'Auto-Tagging'] },
  { id: '6', name: 'Proposal Forge', type: 'proposal', status: 'active', icon: 'FileText', description: 'Generates proposals, quotations, contracts, and onboarding documents', model: 'gpt-4', runCount: 567, successRate: 90.8, lastRun: '15 min ago', capabilities: ['Proposal Generation', 'Quote Builder', 'Contract Drafting', 'Template Engine'] },
  { id: '7', name: 'Meeting Pilot', type: 'meeting', status: 'paused', icon: 'Video', description: 'Schedules meetings and assists with discovery calls via AI transcription', model: 'gpt-4', runCount: 342, successRate: 87.5, lastRun: '1 hr ago', capabilities: ['Calendar Sync', 'Call Transcription', 'Action Items', 'Follow-Up Notes'] },
  { id: '8', name: 'Doc Processor', type: 'document', status: 'active', icon: 'FileSearch', description: 'Processes uploaded data, extracts structured information from PDFs and docs', model: 'gpt-4', runCount: 1234, successRate: 95.2, lastRun: '8 min ago', capabilities: ['OCR', 'Table Extraction', 'Data Parsing', 'Format Conversion'] },
  { id: '9', name: 'Delivery Agent', type: 'delivery', status: 'active', icon: 'Package', description: 'AI-powered service delivery for reports, dashboards, and content generation', model: 'gpt-4', runCount: 789, successRate: 92.4, lastRun: '12 min ago', capabilities: ['Report Generation', 'Dashboard Creation', 'Content Writing', 'Asset Production'] },
  { id: '10', name: 'Revision Handler', type: 'revision', status: 'active', icon: 'GitCompare', description: 'Manages revisions and approval workflows with version tracking', model: 'gpt-4', runCount: 456, successRate: 89.1, lastRun: '25 min ago', capabilities: ['Version Control', 'Feedback Analysis', 'Auto-Revisions', 'Approval Flows'] },
  { id: '11', name: 'Analytics Oracle', type: 'analytics', status: 'active', icon: 'BarChart3', description: 'Continuously optimizes outreach and conversion performance using analytics', model: 'gpt-4', runCount: 2345, successRate: 91.8, lastRun: '1 min ago', capabilities: ['Performance Tracking', 'ROI Analysis', 'Funnel Optimization', 'Predictions'] },
  { id: '12', name: 'Retention Engine', type: 'referral', status: 'active', icon: 'Heart', description: 'Requests testimonials, reviews, referrals and tracks retention opportunities', model: 'gpt-4', runCount: 678, successRate: 85.3, lastRun: '45 min ago', capabilities: ['Testimonial Requests', 'Referral Automation', 'Upsell Detection', 'Churn Prevention'] },
  { id: '13', name: 'Workflow Orchestrator', type: 'workflow', status: 'active', icon: 'Workflow', description: 'Orchestrates complex multi-step automation workflows across agents', model: 'gpt-4', runCount: 3456, successRate: 90.5, lastRun: '2 min ago', capabilities: ['Flow Design', 'Agent Coordination', 'Error Handling', 'Parallel Execution'] },
  { id: '14', name: 'Optimization AI', type: 'optimization', status: 'active', icon: 'Sparkles', description: 'Continuously learns and optimizes all agent performance and strategies', model: 'gpt-4', runCount: 987, successRate: 88.9, lastRun: '5 min ago', capabilities: ['Self-Optimization', 'A/B Testing', 'Strategy Learning', 'Performance Tuning'] },
]

export const campaigns = [
  { id: '1', name: 'SaaS Decision Makers Q2', type: 'email', status: 'active', sent: 1247, opened: 487, replied: 89, converted: 23, openRate: '39.1%', replyRate: '7.1%' },
  { id: '2', name: 'Agency Growth Outreach', type: 'linkedin', status: 'active', sent: 834, opened: 412, replied: 67, converted: 18, openRate: '49.4%', replyRate: '8.0%' },
  { id: '3', name: 'Fintech Leaders Campaign', type: 'multi_channel', status: 'active', sent: 2156, opened: 892, replied: 156, converted: 42, openRate: '41.4%', replyRate: '7.2%' },
  { id: '4', name: 'Healthcare Prospects', type: 'email', status: 'paused', sent: 567, opened: 198, replied: 34, converted: 8, openRate: '34.9%', replyRate: '6.0%' },
  { id: '5', name: 'Re-engagement Sequence', type: 'email', status: 'completed', sent: 2341, opened: 1023, replied: 178, converted: 52, openRate: '43.7%', replyRate: '7.6%' },
]

export const projects = [
  { id: '1', name: 'TechCorp Marketing Dashboard', client: 'TechCorp', type: 'analytics', status: 'in_progress', progress: 72, budget: 24000, deadline: '2026-06-15', deliverables: 5, completedDeliverables: 3 },
  { id: '2', name: 'Innovate Co Brand Identity', client: 'Innovate Co', type: 'design', status: 'review', progress: 90, budget: 48000, deadline: '2026-05-30', deliverables: 8, completedDeliverables: 7 },
  { id: '3', name: 'DataFlow AI Pitch Deck', client: 'DataFlow AI', type: 'presentation', status: 'in_progress', progress: 45, budget: 8000, deadline: '2026-06-01', deliverables: 3, completedDeliverables: 1 },
  { id: '4', name: 'GrowthLab Automation System', client: 'GrowthLab', type: 'automation', status: 'onboarding', progress: 15, budget: 36000, deadline: '2026-07-20', deliverables: 12, completedDeliverables: 0 },
  { id: '5', name: 'LegalWise CRM Setup', client: 'LegalWise', type: 'service', status: 'delivery', progress: 95, budget: 15000, deadline: '2026-05-20', deliverables: 4, completedDeliverables: 4 },
  { id: '6', name: 'ScaleForce Website Redesign', client: 'ScaleForce', type: 'development', status: 'in_progress', progress: 60, budget: 56000, deadline: '2026-06-30', deliverables: 10, completedDeliverables: 5 },
]

export const activities = [
  { id: '1', type: 'lead_created', description: 'New lead discovered: Emily Chen from DataFlow AI', time: '2 min ago', icon: 'UserPlus' },
  { id: '2', type: 'email_sent', description: 'Outreach Pro sent personalized email to Sarah Mitchell', time: '5 min ago', icon: 'Mail' },
  { id: '3', type: 'deal_won', description: 'Deal closed: ScaleForce - $56K', time: '1 hr ago', icon: 'Trophy' },
  { id: '4', type: 'agent_executed', description: 'Lead Scout found 12 new qualified leads', time: '2 hr ago', icon: 'Bot' },
  { id: '5', type: 'proposal_sent', description: 'Proposal sent to Innovate Co - $48K', time: '3 hr ago', icon: 'FileText' },
  { id: '6', type: 'call_scheduled', description: 'Discovery call scheduled with Nina Patel', time: '4 hr ago', icon: 'Phone' },
  { id: '7', type: 'delivery', description: 'Deliverable sent: TechCorp Marketing Dashboard v2', time: '5 hr ago', icon: 'Package' },
  { id: '8', type: 'payment', description: 'Invoice paid: DesignHub - $32K', time: '6 hr ago', icon: 'CreditCard' },
  { id: '9', type: 'referral', description: 'New referral from David Kim: CloudOps VP', time: '8 hr ago', icon: 'Share2' },
  { id: '10', type: 'upsell', description: 'Upsell opportunity detected: GrowthLab automation add-on', time: '1 day ago', icon: 'TrendingUp' },
]

export const revenueData = [
  { month: 'Jan', revenue: 42000, target: 45000, deals: 8 },
  { month: 'Feb', revenue: 51000, target: 48000, deals: 11 },
  { month: 'Mar', revenue: 48000, target: 50000, deals: 9 },
  { month: 'Apr', revenue: 62000, target: 55000, deals: 14 },
  { month: 'May', revenue: 71000, target: 60000, deals: 16 },
  { month: 'Jun', revenue: 58000, target: 62000, deals: 12 },
  { month: 'Jul', revenue: 67000, target: 65000, deals: 15 },
  { month: 'Aug', revenue: 73000, target: 68000, deals: 18 },
  { month: 'Sep', revenue: 81000, target: 72000, deals: 20 },
  { month: 'Oct', revenue: 76000, target: 75000, deals: 17 },
  { month: 'Nov', revenue: 88000, target: 80000, deals: 22 },
  { month: 'Dec', revenue: 95000, target: 85000, deals: 25 },
]

export const conversionFunnel = [
  { stage: 'Leads Generated', value: 2847, percentage: 100 },
  { stage: 'Contacted', value: 1923, percentage: 67.5 },
  { stage: 'Qualified', value: 984, percentage: 34.6 },
  { stage: 'Proposal Sent', value: 547, percentage: 19.2 },
  { stage: 'Negotiation', value: 312, percentage: 11.0 },
  { stage: 'Closed Won', value: 187, percentage: 6.6 },
]

export const workflowTemplates = [
  { id: '1', name: 'Full Sales Pipeline', type: 'lead_generation', description: 'End-to-end lead generation to close', nodes: 8, status: 'active', runs: 234 },
  { id: '2', name: 'Client Onboarding', type: 'onboarding', description: 'Automated onboarding from signed deal to kickoff', nodes: 6, status: 'active', runs: 156 },
  { id: '3', name: 'Service Delivery', type: 'delivery', description: 'Automated delivery with AI-powered generation', nodes: 10, status: 'active', runs: 89 },
  { id: '4', name: 'Retention & Upsell', type: 'retention', description: 'Post-delivery follow-up and upsell automation', nodes: 5, status: 'draft', runs: 0 },
  { id: '5', name: 'Multi-Channel Outreach', type: 'outreach', description: 'Coordinated email, LinkedIn, SMS campaigns', nodes: 7, status: 'active', runs: 312 },
  { id: '6', name: 'Invoice & Payment', type: 'custom', description: 'Automated invoicing and payment collection', nodes: 4, status: 'active', runs: 178 },
]

export const integrations = [
  { id: '1', service: 'LinkedIn', icon: 'Linkedin', status: 'connected', lastSync: '5 min ago', description: 'Lead generation & outreach' },
  { id: '2', service: 'Apollo', icon: 'Search', status: 'connected', lastSync: '10 min ago', description: 'B2B contact database' },
  { id: '3', service: 'Stripe', icon: 'CreditCard', status: 'connected', lastSync: '1 hr ago', description: 'Payment processing' },
  { id: '4', service: 'Google Workspace', icon: 'Mail', status: 'connected', lastSync: '30 min ago', description: 'Email & calendar' },
  { id: '5', service: 'Slack', icon: 'MessageSquare', status: 'connected', lastSync: '2 min ago', description: 'Team notifications' },
  { id: '6', service: 'HubSpot', icon: 'Database', status: 'disconnected', lastSync: 'Never', description: 'CRM sync' },
  { id: '7', service: 'Crunchbase', icon: 'Building2', status: 'connected', lastSync: '15 min ago', description: 'Company intelligence' },
  { id: '8', service: 'Zoom', icon: 'Video', status: 'connected', lastSync: '1 hr ago', description: 'Meeting integration' },
  { id: '9', service: 'Notion', icon: 'BookOpen', status: 'disconnected', lastSync: 'Never', description: 'Knowledge base sync' },
  { id: '10', service: 'Salesforce', icon: 'Cloud', status: 'disconnected', lastSync: 'Never', description: 'Enterprise CRM' },
  { id: '11', service: 'Upwork', icon: 'Briefcase', status: 'connected', lastSync: '20 min ago', description: 'Freelance leads' },
  { id: '12', service: 'Fiverr', icon: 'Star', status: 'disconnected', lastSync: 'Never', description: 'Freelance marketplace' },
]

export const chatMessages = [
  { id: '1', role: 'assistant' as const, content: 'Hello! I\'m your VisionFlow AI assistant. I can help you manage leads, run campaigns, generate proposals, and automate your entire business workflow. What would you like to do?', time: '10:00 AM' },
  { id: '2', role: 'user' as const, content: 'Find me 20 new SaaS leads in the $1M-$10M revenue range that are actively hiring marketing roles', time: '10:01 AM' },
  { id: '3', role: 'assistant' as const, content: 'I\'ve deployed the Lead Scout agent to search across LinkedIn, Apollo, and Crunchbase. Found 23 matches! Here are the top leads:\n\n1. **TechVista Labs** - $4.2M ARR, hiring Head of Growth\n2. **CloudSync Pro** - $7.8M ARR, hiring VP Marketing\n3. **DataPulse** - $2.1M ARR, hiring Marketing Director\n4. **FlowMetrics** - $5.5M ARR, hiring CMO\n5. **NexGen CRM** - $9.2M ARR, hiring Growth Lead\n\nI\'ve scored and enriched all 23 leads. Want me to start personalized outreach to the top 10?', time: '10:02 AM' },
  { id: '4', role: 'user' as const, content: 'Yes, start outreach to the top 10 with our SaaS decision maker template', time: '10:03 AM' },
  { id: '5', role: 'assistant' as const, content: 'Outreach Pro agent activated! I\'ve:\n\n- Customized 10 hyper-personalized emails using prospect intel\n- Scheduled sends for optimal engagement windows\n- Set up 5-step follow-up sequences\n- Added all contacts to the CRM pipeline\n\nFirst emails go out at 9:15 AM tomorrow. I\'ll track opens, clicks, and replies automatically. Want me to set up LinkedIn connection requests too?', time: '10:04 AM' },
]

// ─── Enterprise Docs ──────────────────────────────────────────────────────

export const docsCategories = [
  { id: 'getting-started', name: 'Getting Started', icon: 'Rocket', color: 'bg-vf-emerald/15 text-vf-emerald', docCount: 5, description: 'Everything you need to get started with VisionFlow AI' },
  { id: 'crm', name: 'CRM & Leads', icon: 'Users', color: 'bg-vf-teal/15 text-vf-teal', docCount: 8, description: 'Manage leads, pipelines, and customer relationships' },
  { id: 'ai-agents', name: 'AI Agents', icon: 'Bot', color: 'bg-vf-violet/15 text-vf-violet', docCount: 6, description: 'Configure and deploy AI-powered agents' },
  { id: 'outreach', name: 'Outreach & Campaigns', icon: 'Send', color: 'bg-vf-cyan/15 text-vf-cyan', docCount: 7, description: 'Multi-channel outreach and campaign management' },
  { id: 'workflows', name: 'Workflow Automation', icon: 'Workflow', color: 'bg-vf-amber/15 text-vf-amber', docCount: 5, description: 'Automate complex business processes' },
  { id: 'analytics', name: 'Analytics & Reporting', icon: 'BarChart3', color: 'bg-vf-rose/15 text-vf-rose', docCount: 4, description: 'Insights, reports, and data analysis' },
  { id: 'integrations', name: 'Integrations', icon: 'Link', color: 'bg-blue-500/15 text-blue-500', docCount: 6, description: 'Connect third-party services and tools' },
  { id: 'api', name: 'API Reference', icon: 'Code', color: 'bg-emerald-500/15 text-emerald-500', docCount: 12, description: 'Complete API documentation and endpoints' },
  { id: 'billing', name: 'Billing & Plans', icon: 'CreditCard', color: 'bg-amber-500/15 text-amber-500', docCount: 3, description: 'Plans, pricing, and billing management' },
  { id: 'security', name: 'Security & Compliance', icon: 'Shield', color: 'bg-rose-500/15 text-rose-500', docCount: 4, description: 'Security features, GDPR, and compliance' },
]

export const docsArticles = [
  { id: 'd1', categoryId: 'getting-started', title: 'Quick Start Guide', description: 'Get up and running with VisionFlow AI in under 5 minutes', readTime: '3 min', updatedAt: 'May 10, 2026', views: 2847, author: 'Alex Morgan', version: '2.1', status: 'published' as const, helpful: 94, notHelpful: 6, tags: ['quickstart', 'setup', 'onboarding'], relatedIds: ['d2', 'd3', 'd7'],
    content: `## Welcome to VisionFlow AI\n\nVisionFlow AI is your all-in-one AI-powered sales and business automation platform. This guide will help you get started in under 5 minutes.\n\n### Step 1: Create Your Account\n\nSign up at app.visionflow.ai using your work email. You will receive a verification email within seconds. Click the link to activate your account.\n\n### Step 2: Set Up Your Workspace\n\nAfter verifying your email, you will be prompted to create your workspace. Enter your company name, select your industry, and invite team members. Each workspace is isolated and secure.\n\n### Step 3: Connect Your First Integration\n\nNavigate to Settings > Integrations and connect at least one data source. We recommend starting with LinkedIn or Apollo for lead generation. The setup wizard will guide you through the OAuth flow.\n\n### Step 4: Deploy Your First AI Agent\n\nGo to the AI Agents page and activate the Lead Scout agent. This agent will automatically search your connected data sources for qualified leads based on your ideal customer profile.\n\n### Step 5: Review Your Dashboard\n\nYour dashboard shows real-time KPIs, pipeline metrics, and AI agent activity. Spend a few minutes familiarizing yourself with the layout — it updates automatically as your data flows in.\n\n> **Pro Tip:** Enable desktop notifications in Settings to get instant alerts when your AI agents find high-value leads or when deals close.` },
  { id: 'd2', categoryId: 'getting-started', title: 'Setting Up Your Workspace', description: 'Configure your workspace, team members, and preferences', readTime: '5 min', updatedAt: 'May 8, 2026', views: 1923, author: 'Sarah Chen', version: '1.8', status: 'published' as const, helpful: 89, notHelpful: 11, tags: ['workspace', 'settings', 'team'], relatedIds: ['d1', 'd3'],
    content: `## Workspace Configuration\n\nYour VisionFlow workspace is the central hub for all your team's activity. Proper setup ensures smooth collaboration and accurate AI insights.\n\n### Workspace Settings\n\nNavigate to Settings > Workspace to configure:\n- **Company Profile** — Name, logo, industry, and company size\n- **Time Zone** — Used for scheduling and analytics\n- **Currency** — Set your default currency for deal values\n- **Working Hours** — Define when AI agents should send communications\n\n### Team Management\n\nAdd team members via Settings > Team. Each member can be assigned one of three roles:\n- **Admin** — Full access including billing and integrations\n- **Manager** — Can manage leads, campaigns, and agents\n- **Member** — Can view and edit assigned leads and projects\n\n### Notification Preferences\n\nEach team member can configure their own notification preferences:\n- Email digest frequency (real-time, daily, weekly)\n- In-app notification categories\n- Desktop push notifications\n- Slack integration for team alerts` },
  { id: 'd3', categoryId: 'getting-started', title: 'Connecting Your First Integration', description: 'Link LinkedIn, Apollo, and other data sources to start finding leads', readTime: '4 min', updatedAt: 'May 5, 2026', views: 1654, author: 'Alex Morgan', version: '1.5', status: 'published' as const, helpful: 91, notHelpful: 9, tags: ['integrations', 'setup', 'linkedin', 'apollo'], relatedIds: ['d1', 'd20', 'd21'],
    content: `## Integration Setup\n\nVisionFlow AI connects to 12+ data sources to power your lead generation, outreach, and analytics.\n\n### Available Integrations\n\n| Service | Type | Status |\n|---------|------|--------|\n| LinkedIn | Lead Gen | Connected |\n| Apollo | B2B Database | Connected |\n| Crunchbase | Company Intel | Connected |\n| Google Workspace | Email & Calendar | Connected |\n| Stripe | Payments | Connected |\n\n### Connecting LinkedIn\n\n1. Go to Settings > Integrations > LinkedIn\n2. Click "Connect" and authorize via OAuth 2.0\n3. Select the LinkedIn account to connect\n4. Configure search preferences (industry, title, location)\n5. Enable auto-sync for new connections\n\n### Connecting Apollo\n\n1. Go to Settings > Integrations > Apollo\n2. Enter your Apollo API key\n3. Select the lists to sync\n4. Set up field mapping between Apollo and VisionFlow\n5. Enable real-time sync` },
  { id: 'd4', categoryId: 'crm', title: 'Understanding Lead Scoring', description: 'How our AI scores and qualifies leads automatically', readTime: '6 min', updatedAt: 'May 12, 2026', views: 1234, author: 'Sarah Chen', version: '3.0', status: 'published' as const, helpful: 96, notHelpful: 4, tags: ['crm', 'leads', 'scoring', 'ai'], relatedIds: ['d5', 'd6', 'd7'],
    content: `## AI-Powered Lead Scoring\n\nVisionFlow AI uses a multi-factor scoring model to automatically qualify and prioritize your leads. Scores range from 0 to 100, with higher scores indicating greater conversion likelihood.\n\n### Scoring Factors\n\nOur AI evaluates 15+ signals across four categories:\n\n**1. Firmographic Fit (30% weight)**\n- Company size match\n- Industry alignment\n- Revenue range\n- Technology stack compatibility\n\n**2. Behavioral Signals (30% weight)**\n- Website visits and page views\n- Email engagement patterns\n- Content download activity\n- Social media interactions\n\n**3. Intent Data (25% weight)**\n- Hiring signals for relevant roles\n- Technology adoption signals\n- Funding and growth indicators\n- Competitive solution usage\n\n**4. Engagement Recency (15% weight)**\n- Days since last contact\n- Response rate to outreach\n- Meeting attendance\n- Proposal interaction\n\n### Score Interpretation\n\n| Score Range | Priority | Recommended Action |\n|-------------|----------|--------------------|\n| 90-100 | Hot | Immediate outreach, assign to senior rep |\n| 75-89 | Warm | Priority outreach within 24 hours |\n| 50-74 | Moderate | Add to nurture sequence |\n| 0-49 | Cold | Monitor, periodic check-ins |` },
  { id: 'd5', categoryId: 'crm', title: 'Pipeline Management Best Practices', description: 'Optimize your sales pipeline with proven strategies and AI insights', readTime: '8 min', updatedAt: 'May 9, 2026', views: 987, author: 'Alex Morgan', version: '2.3', status: 'published' as const, helpful: 87, notHelpful: 13, tags: ['crm', 'pipeline', 'sales', 'best-practices'], relatedIds: ['d4', 'd6'],
    content: `## Pipeline Management\n\nEffective pipeline management is crucial for consistent revenue growth. VisionFlow AI provides real-time insights and automation to help you close more deals faster.\n\n### Pipeline Stages\n\nVisionFlow uses a 6-stage pipeline model:\n1. **New Leads** — Freshly discovered or imported leads\n2. **Contacted** — Initial outreach sent\n3. **Qualified** — Confirmed fit and interest\n4. **Proposal** — Formal proposal or quote sent\n5. **Negotiation** — Active deal discussion\n6. **Won** — Deal closed successfully\n\n### Best Practices\n\n**Review Daily** — Check your pipeline every morning. The AI highlights leads that need attention with color-coded priority indicators.\n\n**Use AI Suggestions** — The CRM Brain agent analyzes your pipeline and suggests next actions for each lead, such as "Send follow-up" or "Schedule discovery call."\n\n**Track Velocity** — Monitor the average time leads spend in each stage. Stages with high dwell time often indicate process bottlenecks.\n\n**Maintain Data Hygiene** — Regularly update lead information. The AI enrichment agent can auto-update company data, titles, and contact details.` },
  { id: 'd6', categoryId: 'crm', title: 'Bulk Import & Export Guide', description: 'Import leads from CSV, Salesforce, HubSpot, and other CRMs', readTime: '5 min', updatedAt: 'May 1, 2026', views: 876, author: 'Lisa Wang', version: '1.9', status: 'published' as const, helpful: 82, notHelpful: 18, tags: ['crm', 'import', 'export', 'csv'], relatedIds: ['d4', 'd5'],
    content: `## Bulk Import & Export\n\nEasily migrate your existing lead data into VisionFlow AI or export it for use in other tools.\n\n### CSV Import\n\n1. Navigate to CRM > Import\n2. Download the CSV template\n3. Fill in your data following the template format\n4. Upload the completed CSV\n5. Map columns to VisionFlow fields\n6. Review and confirm the import\n\n**Required Fields:** Name, Email\n**Optional Fields:** Company, Title, Phone, Location, Website, Tags\n\n### Salesforce Import\n\n1. Connect your Salesforce account in Settings > Integrations\n2. Go to CRM > Import > From Salesforce\n3. Select the objects to import (Leads, Contacts, Accounts)\n4. Configure field mapping\n5. Choose import mode (merge or replace)\n\n### Exporting Data\n\nExport any view or filter result as CSV:\n1. Apply your desired filters\n2. Click the Export button\n3. Choose format (CSV or JSON)\n4. Select fields to include\n5. Download the file` },
  { id: 'd7', categoryId: 'ai-agents', title: 'Deploying Your First AI Agent', description: 'Step-by-step guide to activating and configuring AI agents', readTime: '7 min', updatedAt: 'May 11, 2026', views: 1567, author: 'Alex Morgan', version: '2.5', status: 'published' as const, helpful: 93, notHelpful: 7, tags: ['agents', 'ai', 'deployment', 'setup'], relatedIds: ['d1', 'd8', 'd9'],
    content: `## AI Agent Deployment\n\nVisionFlow AI comes with 14 pre-built agents, each designed for a specific business function. This guide walks you through deploying your first agent.\n\n### Available Agent Types\n\n- **Lead Scout** — Automatically discovers qualified leads\n- **Prospect Intel** — Researches companies and contacts\n- **Outreach Pro** — Generates personalized outreach messages\n- **Follow-Up Engine** — Manages follow-up sequences\n- **CRM Brain** — Pipeline analytics and predictions\n- **Proposal Forge** — Generates proposals and contracts\n- **Meeting Pilot** — Schedules meetings and transcribes calls\n- **Doc Processor** — Extracts data from documents\n\n### Deployment Steps\n\n1. Navigate to AI Agents page\n2. Click the agent card you want to deploy\n3. Review the agent description and capabilities\n4. Click "Activate"\n5. Configure the agent settings:\n   - **Model** — Choose GPT-4 or GPT-4 Turbo\n   - **Schedule** — Set run frequency (continuous, hourly, daily)\n   - **Scope** — Define which leads/data the agent can access\n6. Click "Deploy" to start the agent\n\n> **Note:** New agents start in "learning mode" for the first 24 hours, observing your existing data patterns before taking autonomous actions.` },
  { id: 'd8', categoryId: 'ai-agents', title: 'Agent Configuration & Tuning', description: 'Fine-tune temperature, tokens, and auto-run schedules for optimal results', readTime: '6 min', updatedAt: 'May 7, 2026', views: 1123, author: 'Lisa Wang', version: '1.7', status: 'published' as const, helpful: 85, notHelpful: 15, tags: ['agents', 'configuration', 'tuning', 'ai'], relatedIds: ['d7', 'd9'],
    content: `## Agent Configuration\n\nFine-tuning your AI agents ensures they produce the best results for your specific use case. This guide covers all configurable parameters.\n\n### Model Parameters\n\n**Temperature** (0.0 - 2.0)\n- Lower values (0.0-0.3) = More consistent, deterministic outputs\n- Higher values (0.7-1.0) = More creative, varied outputs\n- Recommended: 0.3 for data extraction, 0.7 for content generation\n\n**Max Tokens** (100 - 4000)\n- Controls the maximum length of agent outputs\n- Lead scoring: 500 tokens sufficient\n- Email generation: 1000-2000 tokens recommended\n- Report generation: 2000-4000 tokens\n\n### Auto-Run Schedules\n\nAgents can run on the following schedules:\n- **Continuous** — Runs every 5 minutes (high API usage)\n- **Hourly** — Runs at the top of each hour\n- **Daily** — Runs at a specified time each day\n- **Trigger-based** — Runs when specific events occur\n\n### Success Rate Optimization\n\nMonitor each agent's success rate on the Agents dashboard. If the rate drops below 85%, consider:\n1. Adjusting the temperature\n2. Adding more specific instructions in the agent prompt\n3. Narrowing the data scope` },
  { id: 'd9', categoryId: 'outreach', title: 'Creating Multi-Channel Campaigns', description: 'Build email, LinkedIn, and SMS campaigns with smart sequencing', readTime: '9 min', updatedAt: 'May 6, 2026', views: 1432, author: 'Sarah Chen', version: '3.2', status: 'published' as const, helpful: 92, notHelpful: 8, tags: ['outreach', 'campaigns', 'email', 'linkedin'], relatedIds: ['d7', 'd10', 'd22'],
    content: `## Multi-Channel Campaigns\n\nCreate coordinated outreach campaigns across email, LinkedIn, and SMS channels with AI-powered personalization and smart sequencing.\n\n### Campaign Setup\n\n1. Navigate to Outreach > New Campaign\n2. Select campaign type:\n   - **Email Only** — Traditional email outreach\n   - **LinkedIn Only** — Connection requests and messages\n   - **Multi-Channel** — Coordinated across all channels\n3. Define your target audience using filters\n4. Set campaign timeline and sending windows\n\n### Smart Sequencing\n\nSmart sequences adapt based on recipient engagement:\n\n- **Step 1** — Initial personalized email\n- **Step 2** — LinkedIn connection request (if email unopened after 3 days)\n- **Step 3** — Follow-up email with case study\n- **Step 4** — LinkedIn message referencing the email\n- **Step 5** — Final SMS with meeting link\n\n### Personalization Variables\n\nUse these variables in your templates:\n- {{firstName}}, {{lastName}} — Contact name\n- {{company}} — Company name\n- {{title}} — Job title\n- {{industry}} — Industry\n- {{painPoint}} — AI-detected pain point\n- {{recentNews}} — Recent company news` },
  { id: 'd10', categoryId: 'workflows', title: 'Building Your First Workflow', description: 'Design automated workflows with triggers, actions, and conditions', readTime: '8 min', updatedAt: 'May 4, 2026', views: 1098, author: 'Alex Morgan', version: '2.0', status: 'published' as const, helpful: 88, notHelpful: 12, tags: ['workflows', 'automation', 'triggers'], relatedIds: ['d7', 'd9'],
    content: `## Workflow Builder\n\nThe Workflow Builder lets you create complex automation flows using a visual drag-and-drop interface. Workflows connect triggers, conditions, and actions across your entire sales process.\n\n### Workflow Components\n\n**Triggers** — Events that start the workflow:\n- New lead created\n- Lead score changed\n- Email opened\n- Form submitted\n- Schedule trigger (cron)\n\n**Conditions** — Logic branches:\n- If lead score > 80, do X\n- If industry = "SaaS", do Y\n- If last contact > 7 days, do Z\n\n**Actions** — Things the workflow does:\n- Send email\n- Update lead status\n- Assign to team member\n- Run AI agent\n- Create task\n- Send Slack notification\n\n### Example: Lead Nurture Workflow\n\n1. **Trigger:** New lead with score 50-74\n2. **Action:** Add to "Moderate Priority" list\n3. **Action:** Send welcome email (template: "Industry Intro")\n4. **Wait:** 3 days\n5. **Condition:** If email opened → Send case study\n6. **Condition:** If email not opened → Send LinkedIn connection\n7. **Wait:** 5 days\n8. **Action:** AI agent scores lead again\n9. **Condition:** If score > 80 → Assign to sales rep` },
  { id: 'd11', categoryId: 'api', title: 'REST API Authentication', description: 'How to authenticate API requests using API keys and OAuth', readTime: '4 min', updatedAt: 'May 3, 2026', views: 2345, author: 'Lisa Wang', version: '1.4', status: 'published' as const, helpful: 90, notHelpful: 10, tags: ['api', 'authentication', 'oauth', 'security'], relatedIds: ['d12', 'd23'],
    content: `## API Authentication\n\nAll VisionFlow API requests require authentication. We support two methods: API Keys and OAuth 2.0.\n\n### API Key Authentication\n\nAPI keys are the simplest way to authenticate. Include your key in the Authorization header:\n\n\`\`\`\nAuthorization: Bearer vf_live_sk_abc123def456\n\`\`\`\n\n**Creating an API Key:**\n1. Go to Settings > API Keys\n2. Click "Generate New Key"\n3. Give it a name and set permissions\n4. Copy the key immediately (shown only once)\n\n### OAuth 2.0\n\nFor integrations that need user-level access, use OAuth 2.0:\n\n1. Register your application in Settings > OAuth Apps\n2. Use the authorization URL: \`https://api.visionflow.ai/oauth/authorize\`\n3. Exchange the code for tokens at: \`https://api.visionflow.ai/oauth/token\`\n4. Include the access token in requests\n\n### Rate Limits\n\n| Plan | Requests/min | Requests/day |\n|------|-------------|-------------|\n| Free | 60 | 10,000 |\n| Pro | 300 | 100,000 |\n| Enterprise | 1,000 | Unlimited |` },
  { id: 'd12', categoryId: 'api', title: 'Leads API Endpoints', description: 'Complete reference for lead management API endpoints', readTime: '12 min', updatedAt: 'May 2, 2026', views: 1876, author: 'Lisa Wang', version: '2.8', status: 'published' as const, helpful: 91, notHelpful: 9, tags: ['api', 'leads', 'endpoints', 'reference'], relatedIds: ['d11', 'd4'],
    content: `## Leads API Reference\n\nComplete reference for the VisionFlow Leads API. All endpoints are prefixed with \`/v1/leads\`.\n\n### List Leads\n\n\`\`\`\nGET /v1/leads\n\`\`\`\n\n**Query Parameters:**\n- \`status\` — Filter by status (new, contacted, qualified, proposal, negotiation, won)\n- \`score_min\` — Minimum lead score (0-100)\n- \`score_max\` — Maximum lead score (0-100)\n- \`industry\` — Filter by industry\n- \`source\` — Filter by lead source\n- \`page\` — Page number (default: 1)\n- \`per_page\` — Results per page (default: 25, max: 100)\n\n**Response:**\n\`\`\`json\n{\n  "data": [...],\n  "meta": {\n    "total": 2847,\n    "page": 1,\n    "per_page": 25,\n    "total_pages": 114\n  }\n}\n\`\`\`\n\n### Create Lead\n\n\`\`\`\nPOST /v1/leads\n\`\`\`\n\n**Body:**\n\`\`\`json\n{\n  "name": "John Doe",\n  "email": "john@example.com",\n  "company": "Acme Corp",\n  "title": "CEO",\n  "phone": "+1234567890",\n  "tags": ["enterprise", "saas"]\n}\n\`\`\`` },
  { id: 'd13', categoryId: 'getting-started', title: 'Keyboard Shortcuts & Power User Tips', description: 'Master keyboard shortcuts and hidden features for maximum productivity', readTime: '4 min', updatedAt: 'May 12, 2026', views: 876, author: 'Alex Morgan', version: '1.2', status: 'published' as const, helpful: 97, notHelpful: 3, tags: ['shortcuts', 'power-user', 'productivity'], relatedIds: ['d1', 'd2'],
    content: `## Keyboard Shortcuts\n\nSpeed up your workflow with these keyboard shortcuts:\n\n### Global Shortcuts\n\n| Shortcut | Action |\n|----------|--------|\n| Ctrl+K | Open command palette |\n| Ctrl+/ | Toggle sidebar |\n| Ctrl+J | Quick add lead |\n| Ctrl+Shift+F | Global search |\n| Escape | Close dialog/modal |\n\n### Navigation\n\n| Shortcut | Action |\n|----------|--------|\n| G then D | Go to Dashboard |\n| G then C | Go to CRM |\n| G then A | Go to AI Agents |\n| G then O | Go to Outreach |\n| G then W | Go to Workflows |\n\n### Power User Tips\n\n1. **Command Palette (Ctrl+K)** — Access any page, lead, or action instantly\n2. **Bulk Actions** — Select multiple leads with Shift+Click, then apply actions\n3. **Quick Filters** — Press F on any list view to open filter panel\n4. **AI Chat** — Type "help" in the AI chat for context-aware assistance` },
  { id: 'd14', categoryId: 'getting-started', title: 'Workspace Roles & Permissions', description: 'Understanding role-based access control in VisionFlow AI', readTime: '5 min', updatedAt: 'May 6, 2026', views: 654, author: 'Sarah Chen', version: '1.0', status: 'published' as const, helpful: 86, notHelpful: 14, tags: ['roles', 'permissions', 'security'], relatedIds: ['d2', 'd24'],
    content: `## Roles & Permissions\n\nVisionFlow AI uses role-based access control (RBAC) to manage team member permissions.\n\n### Available Roles\n\n**Admin**\n- Full access to all features\n- Manage billing and subscriptions\n- Add/remove team members\n- Configure integrations\n- Access API keys\n\n**Manager**\n- Manage leads and pipeline\n- Create and run campaigns\n- Configure AI agents\n- View all reports and analytics\n- Cannot modify billing or team\n\n**Member**\n- View and edit assigned leads\n- Use AI chat assistant\n- View own activity reports\n- Cannot access settings or integrations\n\n**Tester**\n- Access to staging features\n- Can report bugs and feedback\n- Limited to test workspace\n- No access to production data` },
  { id: 'd15', categoryId: 'crm', title: 'Custom Fields & Lead Properties', description: 'Create custom fields to track the data that matters most to your business', readTime: '5 min', updatedAt: 'May 8, 2026', views: 543, author: 'Lisa Wang', version: '1.3', status: 'published' as const, helpful: 80, notHelpful: 20, tags: ['crm', 'custom-fields', 'properties'], relatedIds: ['d4', 'd6'],
    content: `## Custom Fields\n\nExtend VisionFlow's lead model with custom fields tailored to your business needs.\n\n### Creating Custom Fields\n\n1. Navigate to Settings > Custom Fields\n2. Click "Add Field"\n3. Choose field type:\n   - Text, Number, Date, Select, Multi-Select\n   - URL, Email, Phone, Currency\n   - Formula (computed from other fields)\n4. Set visibility and required status\n5. Assign to lead, company, or deal objects\n\n### Field Types\n\n- **Text** — Short text input (max 255 chars)\n- **Number** — Numeric values with optional formatting\n- **Date** — Date picker with optional time\n- **Select** — Single choice from predefined options\n- **Multi-Select** — Multiple choices with tags UI\n- **Formula** — Auto-calculated from other fields\n\n### Using Custom Fields\n\nCustom fields appear in the lead detail panel, CSV imports/exports, API responses, and can be used in workflow conditions and AI agent prompts.` },
  { id: 'd16', categoryId: 'crm', title: 'Email Tracking & Engagement Metrics', description: 'Monitor email opens, clicks, and replies to optimize your outreach', readTime: '6 min', updatedAt: 'May 4, 2026', views: 789, author: 'Sarah Chen', version: '1.6', status: 'published' as const, helpful: 83, notHelpful: 17, tags: ['crm', 'email', 'tracking', 'metrics'], relatedIds: ['d5', 'd9'],
    content: `## Email Tracking\n\nVisionFlow provides real-time email tracking across all your outreach campaigns and individual emails.\n\n### Tracked Events\n\n- **Sent** — Email successfully delivered\n- **Delivered** — Confirmed delivery to inbox\n- **Opened** — Recipient opened the email (tracked via pixel)\n- **Clicked** — Recipient clicked a link in the email\n- **Replied** — Recipient sent a reply\n- **Bounced** — Email could not be delivered\n- **Unsubscribed** — Recipient clicked unsubscribe\n\n### Engagement Score\n\nEach lead receives an engagement score based on their email interactions:\n- Open: +5 points\n- Click: +15 points\n- Reply: +25 points\n- Unsubscribe: -50 points\n\n### Real-Time Notifications\n\nGet instant alerts when important leads engage with your emails. Configure notification rules in Settings > Notifications > Email Tracking.` },
  { id: 'd17', categoryId: 'crm', title: 'Lead Nurturing Sequences', description: 'Build automated nurture sequences to warm up cold leads over time', readTime: '7 min', updatedAt: 'May 3, 2026', views: 612, author: 'Alex Morgan', version: '2.1', status: 'published' as const, helpful: 84, notHelpful: 16, tags: ['crm', 'nurture', 'sequences', 'automation'], relatedIds: ['d5', 'd10', 'd9'],
    content: `## Lead Nurturing\n\nAutomated nurturing sequences help you stay engaged with leads over time without manual effort.\n\n### Building a Nurture Sequence\n\n1. Go to CRM > Nurture Sequences > Create New\n2. Define entry criteria (which leads enter this sequence)\n3. Add steps with delays:\n   - Day 0: Welcome email\n   - Day 3: Industry case study\n   - Day 7: ROI calculator link\n   - Day 14: Invitation to webinar\n   - Day 21: Personal check-in\n4. Set exit criteria (score threshold, reply, deal creation)\n5. Activate the sequence\n\n### AI-Optimized Timing\n\nThe Follow-Up Engine agent analyzes each lead's engagement patterns and adjusts timing automatically:\n- Sends emails at the lead's most likely open time\n- Increases frequency for highly engaged leads\n- Pauses sequence if the lead shows negative signals` },
  { id: 'd18', categoryId: 'ai-agents', title: 'Agent Memory & Context Management', description: 'How AI agents maintain context and learn from interactions', readTime: '5 min', updatedAt: 'May 10, 2026', views: 934, author: 'Lisa Wang', version: '1.1', status: 'draft' as const, helpful: 78, notHelpful: 22, tags: ['agents', 'memory', 'context', 'ai'], relatedIds: ['d7', 'd8'],
    content: `## Agent Memory\n\nVisionFlow AI agents maintain contextual memory across interactions, enabling increasingly personalized and accurate outputs over time.\n\n### Memory Types\n\n**Short-Term Memory** — The agent's current working context within a session. Cleared when the agent run completes.\n\n**Long-Term Memory** — Persistent learnings stored across sessions. Includes:\n- Communication style preferences per lead\n- Successful outreach patterns\n- Industry-specific terminology\n- Team workflow patterns\n\n**Shared Memory** — Knowledge shared across all agents. When Lead Scout learns a new company detail, CRM Brain can immediately use it.\n\n### Memory Management\n\n- View agent memory in Settings > Agents > Memory\n- Clear specific memories or reset all memory\n- Export memory for audit purposes\n- Memory is encrypted at rest and in transit` },
  { id: 'd19', categoryId: 'ai-agents', title: 'Custom Agent Creation', description: 'Build custom AI agents for your specific business workflows', readTime: '10 min', updatedAt: 'May 9, 2026', views: 1456, author: 'Alex Morgan', version: '2.2', status: 'published' as const, helpful: 95, notHelpful: 5, tags: ['agents', 'custom', 'creation', 'advanced'], relatedIds: ['d7', 'd8', 'd10'],
    content: `## Custom Agents\n\nWhile VisionFlow includes 14 pre-built agents, you can also create custom agents tailored to your unique business needs.\n\n### Creating a Custom Agent\n\n1. Navigate to AI Agents > Create Custom\n2. Define the agent:\n   - **Name** — e.g., "Competitor Watchdog"\n   - **Description** — What the agent does\n   - **Trigger** — When it should run\n   - **Instructions** — Detailed prompt for the AI\n3. Configure capabilities:\n   - Web search access\n   - CRM data access\n   - Email sending permissions\n   - Slack notification access\n4. Set guardrails:\n   - Approval required before sending\n   - Maximum actions per run\n   - Restricted data access\n5. Test with sample data\n6. Deploy to production\n\n### Example: Competitor Watchdog\n\n\`\`\`\nName: Competitor Watchdog\nTrigger: Daily at 9:00 AM\nInstructions: Search for recent news about [competitor names].\nIf a competitor launches a new feature or changes pricing,\nsend a Slack alert to #competitive-intel with a summary\nand suggest talking points for our sales team.\n\`\`\`` },
  { id: 'd20', categoryId: 'integrations', title: 'LinkedIn Integration Deep Dive', description: 'Advanced configuration for LinkedIn Sales Navigator and messaging', readTime: '7 min', updatedAt: 'May 7, 2026', views: 1098, author: 'Sarah Chen', version: '1.9', status: 'published' as const, helpful: 88, notHelpful: 12, tags: ['integrations', 'linkedin', 'sales-navigator'], relatedIds: ['d3', 'd9'],
    content: `## LinkedIn Integration\n\nThe LinkedIn integration powers lead discovery, connection management, and automated messaging directly from VisionFlow.\n\n### Sales Navigator Sync\n\nConnect your LinkedIn Sales Navigator account to:\n- Auto-import saved leads and accounts\n- Sync lead lists bidirectionally\n- Access InMail templates from VisionFlow\n- Track profile views and engagement\n\n### Automated Connection Requests\n\nConfigure the Outreach Pro agent to send personalized connection requests:\n- Daily limit: 20-50 (LinkedIn safe limits)\n- Custom message templates with personalization\n- Smart timing based on target's timezone\n- Auto-withdraw unaccepted requests after 30 days\n\n### Compliance\n\nThe integration follows LinkedIn's Terms of Service:\n- Human-like sending patterns\n- Randomized delays between actions\n- Daily and hourly rate limits\n- Automatic pause if rate limit warnings detected` },
  { id: 'd21', categoryId: 'integrations', title: 'Slack Integration Setup', description: 'Connect Slack for real-time notifications and team collaboration', readTime: '3 min', updatedAt: 'May 5, 2026', views: 765, author: 'Mike Johnson', version: '1.2', status: 'published' as const, helpful: 92, notHelpful: 8, tags: ['integrations', 'slack', 'notifications'], relatedIds: ['d3', 'd20'],
    content: `## Slack Integration\n\nReceive real-time VisionFlow notifications directly in your Slack workspace.\n\n### Setup\n\n1. Go to Settings > Integrations > Slack\n2. Click "Add to Slack"\n3. Select your Slack workspace\n4. Choose the channel for notifications\n5. Configure notification types:\n   - New lead alerts\n   - Deal stage changes\n   - AI agent completions\n   - Campaign milestones\n   - Meeting reminders\n\n### Slash Commands\n\nOnce installed, use these commands in Slack:\n- \`/vf leads\` — Show today's new leads\n- \`/vf pipeline\` — Pipeline summary\n- \`/vf agent status\` — Agent health check\n- \`/vf help\` — Show all commands` },
  { id: 'd22', categoryId: 'outreach', title: 'A/B Testing Outreach Templates', description: 'Test different subject lines, body copy, and send times to optimize results', readTime: '6 min', updatedAt: 'May 2, 2026', views: 876, author: 'Sarah Chen', version: '1.4', status: 'published' as const, helpful: 85, notHelpful: 15, tags: ['outreach', 'a-b-testing', 'optimization'], relatedIds: ['d9', 'd16'],
    content: `## A/B Testing\n\nOptimize your outreach by testing different variations and letting the AI determine the winner.\n\n### Setting Up a Test\n\n1. Create a campaign with at least 2 template variants\n2. Configure the test:\n   - **Split ratio** — Even 50/50 or custom\n   - **Sample size** — Minimum leads before declaring winner\n   - **Metric** — Open rate, reply rate, or click rate\n   - **Duration** — How long to run the test\n3. Launch the campaign\n4. The AI monitors results and auto-selects the winner\n\n### Best Practices\n\n- Test one variable at a time (subject line, CTA, send time)\n- Use at least 100 recipients per variant for statistical significance\n- Run tests for at least 3 business days\n- Document learnings in campaign notes` },
  { id: 'd23', categoryId: 'api', title: 'Webhooks & Event Subscriptions', description: 'Subscribe to real-time events via webhooks for custom integrations', readTime: '5 min', updatedAt: 'May 1, 2026', views: 1567, author: 'Lisa Wang', version: '1.6', status: 'published' as const, helpful: 87, notHelpful: 13, tags: ['api', 'webhooks', 'events', 'integrations'], relatedIds: ['d11', 'd12'],
    content: `## Webhooks\n\nSubscribe to real-time events and receive HTTP POST callbacks to your server whenever something happens in VisionFlow.\n\n### Available Events\n\n- \`lead.created\` — New lead added\n- \`lead.updated\` — Lead data changed\n- \`lead.score_changed\` — Lead score updated\n- \`deal.stage_changed\` — Deal moved to new stage\n- \`deal.won\` — Deal closed successfully\n- \`email.opened\` — Recipient opened email\n- \`email.replied\` — Recipient replied\n- \`agent.completed\` — Agent run finished\n- \`workflow.triggered\` — Workflow started\n\n### Setup\n\n1. Go to Settings > Webhooks\n2. Click "Add Endpoint"\n3. Enter your HTTPS URL\n4. Select events to subscribe to\n5. Copy the signing secret for verification\n\n### Verification\n\nEach webhook includes a signature header for verification:\n\`\`\`\nX-VF-Signature: sha256=a1b2c3d4...\n\`\`\`\n\nVerify using HMAC-SHA256 with your signing secret.` },
  { id: 'd24', categoryId: 'security', title: 'Data Encryption & Privacy', description: 'How VisionFlow protects your data at rest and in transit', readTime: '5 min', updatedAt: 'May 10, 2026', views: 1890, author: 'Lisa Wang', version: '2.0', status: 'published' as const, helpful: 94, notHelpful: 6, tags: ['security', 'encryption', 'privacy', 'compliance'], relatedIds: ['d14', 'd11'],
    content: `## Data Security\n\nVisionFlow AI implements enterprise-grade security measures to protect your data at every layer.\n\n### Encryption\n\n- **At Rest** — AES-256 encryption for all stored data\n- **In Transit** — TLS 1.3 for all API and web traffic\n- **Backups** — Encrypted with separate key management\n- **PII Fields** — Additional field-level encryption for sensitive data\n\n### Access Control\n\n- Role-based access control (RBAC) with granular permissions\n- Multi-factor authentication (MFA) required for admin actions\n- IP whitelisting for API access\n- Session management with automatic timeout\n\n### Compliance\n\n- SOC 2 Type II certified\n- GDPR compliant with DPA available\n- CCPA compliant\n- Data residency options (US, EU, APAC)\n\n### Data Retention\n\n- Active data: Retained while account is active\n- Deleted data: Purged within 30 days\n- Backup data: 90-day retention with encrypted storage\n- Audit logs: 1-year retention by default` },
  { id: 'd25', categoryId: 'security', title: 'SOC 2 Compliance Report', description: 'Overview of our SOC 2 Type II certification and audit findings', readTime: '8 min', updatedAt: 'Apr 28, 2026', views: 567, author: 'Lisa Wang', version: '1.0', status: 'published' as const, helpful: 91, notHelpful: 9, tags: ['security', 'soc2', 'compliance', 'audit'], relatedIds: ['d24'],
    content: `## SOC 2 Compliance\n\nVisionFlow AI is SOC 2 Type II certified, demonstrating our commitment to security, availability, and confidentiality.\n\n### Certification Details\n\n- **Type:** SOC 2 Type II\n- **Auditor:** Independent third-party CPA firm\n- **Period:** January 2025 - December 2025\n- **Trust Services:** Security, Availability, Confidentiality\n\n### Key Controls\n\n1. **Access Management** — Automated provisioning and deprovisioning\n2. **Change Management** — All changes go through code review and approval\n3. **Incident Response** — 24/7 monitoring with <15 min response time\n4. **Vulnerability Management** — Continuous scanning and quarterly pen tests\n5. **Data Encryption** — AES-256 at rest, TLS 1.3 in transit\n\n### Requesting the Report\n\nEnterprise customers can request the full SOC 2 report by contacting your account manager or emailing security@visionflow.ai. NDA required.` },
  { id: 'd26', categoryId: 'analytics', title: 'Dashboard Metrics Explained', description: 'Understanding each metric on your VisionFlow dashboard', readTime: '6 min', updatedAt: 'May 8, 2026', views: 1234, author: 'Alex Morgan', version: '1.5', status: 'published' as const, helpful: 89, notHelpful: 11, tags: ['analytics', 'dashboard', 'metrics', 'kpis'], relatedIds: ['d4', 'd10'],
    content: `## Dashboard Metrics\n\nYour VisionFlow dashboard provides real-time KPIs that reflect your business performance.\n\n### Key Metrics\n\n**Total Leads** — The total number of leads in your pipeline across all stages. This includes leads from all sources and team members.\n\n**Active Deals** — The total value of deals currently in Proposal or Negotiation stages. This represents your near-term revenue pipeline.\n\n**Conversion Rate** — The percentage of leads that progress from initial contact to closed deal. Calculated as: (Won Deals / Total Leads) x 100.\n\n**Active Projects** — Current client projects in delivery phase. Each project may have multiple deliverables tracked separately.\n\n**AI Tasks Done** — Total autonomous actions completed by your AI agents. Includes lead research, email sends, follow-ups, and data enrichment.\n\n**Revenue MTD** — Month-to-date revenue from closed deals. Compared against your monthly target for at-a-glance performance tracking.\n\n### Customizing Your Dashboard\n\nRearrange metric cards by dragging, add custom KPIs from Settings > Dashboard, and set your preferred time range for trend calculations.` },
  { id: 'd27', categoryId: 'workflows', title: 'Advanced Workflow Patterns', description: 'Complex automation patterns including parallel execution, error handling, and loops', readTime: '10 min', updatedAt: 'May 5, 2026', views: 678, author: 'Alex Morgan', version: '2.4', status: 'draft' as const, helpful: 76, notHelpful: 24, tags: ['workflows', 'advanced', 'patterns', 'automation'], relatedIds: ['d10', 'd7'],
    content: `## Advanced Workflows\n\nTake your automation to the next level with advanced workflow patterns.\n\n### Parallel Execution\n\nRun multiple actions simultaneously instead of sequentially:\n\n1. Trigger: New qualified lead\n2. Parallel branch A: Send welcome email\n3. Parallel branch B: Enrich lead data via AI\n4. Parallel branch C: Create Slack notification\n5. Sync point: Wait for all branches\n6. Next step: Assign to sales rep\n\n### Error Handling\n\nAdd error handlers to workflow steps:\n- **Retry** — Automatically retry failed steps (up to 3 times)\n- **Fallback** — Execute alternative action on failure\n- **Notify** — Send alert to team on repeated failures\n- **Skip** — Log error and continue workflow\n\n### Loops\n\nIterate over lists of items:\n- For each lead in a list, send personalized email\n- For each deliverable, check completion status\n- For each integration, verify connection health` },
  { id: 'd28', categoryId: 'billing', title: 'Plan Comparison & Upgrading', description: 'Compare plans and understand upgrade options for your team', readTime: '4 min', updatedAt: 'May 7, 2026', views: 2345, author: 'Alex Morgan', version: '1.8', status: 'published' as const, helpful: 88, notHelpful: 12, tags: ['billing', 'plans', 'pricing', 'upgrade'], relatedIds: ['d29'],
    content: `## Plan Comparison\n\nChoose the plan that fits your team's needs.\n\n| Feature | Starter | Pro | Enterprise |\n|---------|---------|-----|-----------|\n| Leads | 500 | 10,000 | Unlimited |\n| AI Agents | 3 | 10 | Unlimited |\n| Team Members | 2 | 10 | Unlimited |\n| Campaigns | 5 | 50 | Unlimited |\n| API Access | Read-only | Full | Full + Priority |\n| Support | Email | Priority Chat | Dedicated CSM |\n| Price | $49/mo | $199/mo | Custom |\n\n### Upgrading\n\n1. Navigate to Settings > Billing\n2. Click "Upgrade Plan"\n3. Select your new plan\n4. Confirm payment method\n5. Changes take effect immediately\n\nProrated credits are applied for unused time on your current plan.` },
  { id: 'd29', categoryId: 'billing', title: 'Invoice & Payment Management', description: 'View invoices, update payment methods, and manage billing', readTime: '3 min', updatedAt: 'May 4, 2026', views: 1567, author: 'Sarah Chen', version: '1.3', status: 'published' as const, helpful: 86, notHelpful: 14, tags: ['billing', 'invoices', 'payments'], relatedIds: ['d28'],
    content: `## Invoice Management\n\nView and manage all your billing information in one place.\n\n### Viewing Invoices\n\n1. Go to Settings > Billing > Invoices\n2. Browse by date or search by invoice number\n3. Click any invoice to view details or download PDF\n\n### Payment Methods\n\n- **Credit Card** — Visa, Mastercard, Amex accepted\n- **ACH/Bank Transfer** — Available for Enterprise plans\n- **Wire Transfer** — For annual prepayment\n\n### Updating Payment\n\n1. Go to Settings > Billing > Payment Method\n2. Click "Update"\n3. Enter new card details\n4. Save — next invoice uses the new method\n\n### Failed Payments\n\nIf a payment fails:\n- We retry after 3 days\n- You receive an email notification\n- Service continues for 7 days\n- After 7 days, account is downgraded to Starter` },
  { id: 'd30', categoryId: 'analytics', title: 'Custom Reports & Data Export', description: 'Build custom reports and schedule automated data exports', readTime: '7 min', updatedAt: 'May 6, 2026', views: 876, author: 'Alex Morgan', version: '1.4', status: 'published' as const, helpful: 82, notHelpful: 18, tags: ['analytics', 'reports', 'export', 'custom'], relatedIds: ['d26'],
    content: `## Custom Reports\n\nCreate tailored reports that focus on the metrics that matter most to your business.\n\n### Report Builder\n\n1. Navigate to Analytics > Reports > Create New\n2. Select data source (Leads, Deals, Campaigns, Agents)\n3. Choose metrics and dimensions\n4. Apply filters and date range\n5. Add visualizations (charts, tables, KPIs)\n6. Save and schedule\n\n### Scheduled Exports\n\nSet up automated report delivery:\n- **Frequency** — Daily, weekly, monthly\n- **Format** — PDF, CSV, Google Sheets\n- **Recipients** — Team members or external emails\n- **Filters** — Pre-applied filters for consistent reporting\n\n### Report Templates\n\nPre-built templates for common use cases:\n- Weekly Pipeline Summary\n- Monthly Revenue Report\n- Agent Performance Dashboard\n- Campaign ROI Analysis` },
]

export const docsVersions = [
  { id: 'v1', articleId: 'd1', version: '1.0', author: 'Alex Morgan', updatedAt: 'Apr 1, 2026', changes: 'Initial version' },
  { id: 'v2', articleId: 'd1', version: '2.0', author: 'Alex Morgan', updatedAt: 'May 1, 2026', changes: 'Added Step 4 and Step 5, updated screenshots' },
  { id: 'v3', articleId: 'd1', version: '2.1', author: 'Alex Morgan', updatedAt: 'May 10, 2026', changes: 'Added pro tip, fixed typo in Step 3' },
  { id: 'v4', articleId: 'd4', version: '1.0', author: 'Sarah Chen', updatedAt: 'Mar 15, 2026', changes: 'Initial version with basic scoring factors' },
  { id: 'v5', articleId: 'd4', version: '2.0', author: 'Sarah Chen', updatedAt: 'Apr 20, 2026', changes: 'Added intent data and engagement recency factors' },
  { id: 'v6', articleId: 'd4', version: '3.0', author: 'Sarah Chen', updatedAt: 'May 12, 2026', changes: 'Complete rewrite with updated scoring weights and table' },
  { id: 'v7', articleId: 'd7', version: '1.0', author: 'Alex Morgan', updatedAt: 'Mar 22, 2026', changes: 'Initial agent deployment guide' },
  { id: 'v8', articleId: 'd7', version: '2.0', author: 'Alex Morgan', updatedAt: 'Apr 28, 2026', changes: 'Added learning mode explanation, updated agent list' },
  { id: 'v9', articleId: 'd7', version: '2.5', author: 'Alex Morgan', updatedAt: 'May 11, 2026', changes: 'Added GPT-4 Turbo option, updated deployment steps' },
  { id: 'v10', articleId: 'd9', version: '1.0', author: 'Sarah Chen', updatedAt: 'Feb 10, 2026', changes: 'Initial multi-channel campaign guide' },
  { id: 'v11', articleId: 'd9', version: '2.0', author: 'Sarah Chen', updatedAt: 'Apr 5, 2026', changes: 'Added smart sequencing and personalization variables' },
  { id: 'v12', articleId: 'd9', version: '3.2', author: 'Sarah Chen', updatedAt: 'May 6, 2026', changes: 'Complete rewrite with step-by-step sequences' },
]

// ─── Team Accounts (enhanced) ─────────────────────────────────────────────

export const teamAccounts = [
  // ─── Team Members ───────────────────────────────────────────────────
  { id: '1', name: 'Alex Morgan', email: 'alex@visionflow.ai', role: 'Admin', status: 'online', avatar: 'AM', department: 'Leadership', lastActive: 'Now', isTester: false },
  { id: '2', name: 'Sarah Chen', email: 'sarah@visionflow.ai', role: 'Manager', status: 'online', avatar: 'SC', department: 'Sales', lastActive: 'Now', isTester: false },
  { id: '3', name: 'Mike Johnson', email: 'mike@visionflow.ai', role: 'Member', status: 'offline', avatar: 'MJ', department: 'Marketing', lastActive: '3 hrs ago', isTester: false },
  { id: '4', name: 'Lisa Wang', email: 'lisa@visionflow.ai', role: 'Member', status: 'online', avatar: 'LW', department: 'Engineering', lastActive: 'Now', isTester: false },
  // ─── Tester Accounts (bcrypt hashed passwords in database) ──────────
  { id: '5', name: 'Prince Chauhan', email: 'prince.testing@visionflow.ai', role: 'Tester', status: 'online', avatar: 'PC', department: 'QA & Testing', lastActive: 'Now', isTester: true },
  { id: '6', name: 'Ronak Jain', email: 'ronak.testing@visionflow.ai', role: 'Tester', status: 'online', avatar: 'RJ', department: 'QA & Testing', lastActive: '5 min ago', isTester: true },
  { id: '7', name: 'Mehul Kumar', email: 'mehul.testing@visionflow.ai', role: 'Tester', status: 'online', avatar: 'MK', department: 'QA & Testing', lastActive: '10 min ago', isTester: true },
]

// ─── Bug Tracking ─────────────────────────────────────────────────────────

export const bugs = [
  { id: 'BUG-001', title: 'CRM pipeline drag-and-drop not working on Safari', status: 'open', priority: 'high', assignee: 'Lisa Wang', reporter: 'Prince Chauhan', createdAt: '2026-05-12', updatedAt: '2026-05-13', labels: ['bug', 'crm', 'safari'], description: 'When attempting to drag leads between pipeline columns on Safari 17.4, the drag operation starts but the drop target does not register the drop event. Works correctly on Chrome and Firefox.' },
  { id: 'BUG-002', title: 'Revenue chart tooltip shows wrong month on hover', status: 'in-progress', priority: 'medium', assignee: 'Mike Johnson', reporter: 'Alex Morgan', createdAt: '2026-05-10', updatedAt: '2026-05-12', labels: ['bug', 'dashboard', 'charts'], description: 'The revenue overview chart on the dashboard shows the previous month in the tooltip when hovering over data points. Off-by-one error in the tooltip formatter.' },
  { id: 'BUG-003', title: 'Email template variables not replacing for LinkedIn contacts', status: 'open', priority: 'high', assignee: 'Sarah Chen', reporter: 'Ronak Jain', createdAt: '2026-05-11', updatedAt: '2026-05-13', labels: ['bug', 'outreach', 'templates'], description: 'When sending outreach using the "SaaS Decision Maker" template to LinkedIn-sourced contacts, {{company}} and {{title}} variables remain unreplaced in the sent email.' },
  { id: 'BUG-004', title: 'Agent success rate calculation includes cancelled runs', status: 'resolved', priority: 'low', assignee: 'Lisa Wang', reporter: 'Mehul Kumar', createdAt: '2026-05-08', updatedAt: '2026-05-11', labels: ['bug', 'agents', 'analytics'], description: 'The agent success rate metric was including cancelled runs in the denominator, making success rates appear lower than actual. Fixed by filtering cancelled runs from the calculation.' },
  { id: 'BUG-005', title: 'Workflow builder node properties panel not scrollable', status: 'open', priority: 'medium', assignee: 'Mike Johnson', reporter: 'Prince Chauhan', createdAt: '2026-05-13', updatedAt: '2026-05-13', labels: ['bug', 'workflows', 'ui'], description: 'When a workflow has many conditions in the node properties panel, the panel content overflows without a scrollbar, making it impossible to see or edit all conditions.' },
  { id: 'BUG-006', title: 'Dark mode toggle causes flash of unstyled content', status: 'resolved', priority: 'low', assignee: 'Lisa Wang', reporter: 'Ronak Jain', createdAt: '2026-05-06', updatedAt: '2026-05-09', labels: ['bug', 'settings', 'theme'], description: 'Switching between light and dark mode causes a brief flash of unstyled content (FOUC). Should apply theme class to document root before render.' },
  { id: 'BUG-007', title: 'Lead export CSV has incorrect encoding for special characters', status: 'in-progress', priority: 'medium', assignee: 'Sarah Chen', reporter: 'Alex Morgan', createdAt: '2026-05-09', updatedAt: '2026-05-12', labels: ['bug', 'crm', 'export'], description: 'Exporting leads with names containing accented characters (e.g., "René", "Müller") results in garbled text in the CSV file. UTF-8 BOM header needs to be added.' },
  { id: 'BUG-008', title: 'Notification bell count resets on page navigation', status: 'open', priority: 'low', assignee: 'Mike Johnson', reporter: 'Mehul Kumar', createdAt: '2026-05-13', updatedAt: '2026-05-13', labels: ['bug', 'notifications'], description: 'The notification badge count in the header resets to 0 when navigating between pages, even when there are unread notifications. State persistence issue in Zustand store.' },
]

// ─── Feedback ──────────────────────────────────────────────────────────────

export const feedbackItems = [
  { id: 'fb1', title: 'Add Kanban drag-and-drop for CRM pipeline', category: 'feature', status: 'planned', upvotes: 47, author: 'Sarah Chen', createdAt: '2026-04-20', description: 'Allow dragging leads between pipeline stages instead of using the status dropdown. This would make the CRM much more intuitive and faster to use.' },
  { id: 'fb2', title: 'Dark mode support for the entire app', category: 'feature', status: 'completed', upvotes: 89, author: 'Mike Johnson', createdAt: '2026-03-15', description: 'Full dark mode support across all pages including the landing page, dashboard, CRM, and settings. Currently only partially supported.' },
  { id: 'fb3', title: 'Bulk email sending from CRM', category: 'feature', status: 'planned', upvotes: 34, author: 'Alex Morgan', createdAt: '2026-05-01', description: 'Ability to select multiple leads and send a personalized email to all of them at once, with template variables auto-filled per lead.' },
  { id: 'fb4', title: 'Campaign performance is slow with 10K+ contacts', category: 'bug', status: 'in-progress', upvotes: 22, author: 'Lisa Wang', createdAt: '2026-04-28', description: 'When a campaign has more than 10,000 contacts, the campaign detail page takes over 5 seconds to load. Need pagination or lazy loading for large campaigns.' },
  { id: 'fb5', title: 'Mobile sidebar overlaps content on tablets', category: 'bug', status: 'resolved', upvotes: 15, author: 'QA Tester Alpha', createdAt: '2026-04-15', description: 'On iPad-sized screens (768px-1024px), the sidebar overlay covers content instead of pushing it. The sidebar should collapse properly on tablet viewports.' },
  { id: 'fb6', title: 'AI agent chat should support file uploads', category: 'feature', status: 'review', upvotes: 56, author: 'Sarah Chen', createdAt: '2026-05-05', description: 'Allow uploading PDFs, spreadsheets, and images to the AI chat so agents can analyze and process uploaded files directly in the conversation.' },
  { id: 'fb7', title: 'Weekly digest email should include AI insights', category: 'improvement', status: 'planned', upvotes: 28, author: 'Alex Morgan', createdAt: '2026-04-25', description: 'The weekly digest email currently only shows raw numbers. It should include AI-generated insights like "Lead quality improved 15% this week" and suggested actions.' },
  { id: 'fb8', title: 'Add Gantt chart view to projects', category: 'feature', status: 'review', upvotes: 41, author: 'Mike Johnson', createdAt: '2026-05-08', description: 'A Gantt chart view for projects would help visualize timelines, dependencies, and overlapping work across multiple projects.' },
]

// ─── Blog Posts (written from app, displayed on landing) ───────────────────

export const blogPosts = [
  { id: 'b1', title: 'How AI Agents Are Replacing SDR Teams in 2026', excerpt: 'The traditional SDR model is dying. Here is how AI-powered agents are finding, qualifying, and engaging leads 24/7 without human intervention — and why agencies that adopt early are winning big.', author: 'Alex Morgan', date: 'May 12, 2026', readTime: '6 min', category: 'AI Strategy', image: 'strategy', featured: true },
  { id: 'b2', title: '5 Multi-Channel Outreach Strategies That Actually Work', excerpt: 'We analyzed 10,000 campaigns across our platform and found five patterns that consistently outperform everything else. The data might surprise you — especially strategy number three.', author: 'Sarah Chen', date: 'May 9, 2026', readTime: '8 min', category: 'Outreach', image: 'outreach', featured: true },
  { id: 'b3', title: 'The Complete Guide to AI-Powered Lead Scoring', excerpt: 'Stop guessing which leads are worth your time. Our multi-factor scoring model evaluates 15+ signals to predict conversion likelihood with 94% accuracy. Here is exactly how it works.', author: 'Sarah Chen', date: 'May 5, 2026', readTime: '7 min', category: 'CRM', image: 'crm', featured: false },
  { id: 'b4', title: 'Why Your Follow-Up Sequence Is Leaving Money on the Table', excerpt: '80% of sales require 5+ follow-ups, but 44% of reps give up after one. The Follow-Up Engine agent never gives up — and it is recovering $2.3M in missed revenue per quarter for our users.', author: 'Alex Morgan', date: 'May 2, 2026', readTime: '5 min', category: 'Automation', image: 'automation', featured: false },
  { id: 'b5', title: 'Building Custom AI Agents for Niche Industries', excerpt: 'Out-of-the-box agents are powerful, but custom agents built for your specific industry vertical can achieve 40% higher conversion rates. Here is a step-by-step walkthrough for building yours.', author: 'Lisa Wang', date: 'Apr 28, 2026', readTime: '10 min', category: 'AI Strategy', image: 'custom', featured: true },
  { id: 'b6', title: 'From $0 to $128K MRR: A Growth Story with VisionFlow', excerpt: 'How a 3-person agency scaled from zero to $128K monthly recurring revenue in 8 months using AI-powered lead generation, automated outreach, and workflow orchestration.', author: 'Alex Morgan', date: 'Apr 24, 2026', readTime: '9 min', category: 'Case Study', image: 'growth', featured: false },
]

// ─── Dashboard: AI Usage Metrics ──────────────────────────────────────────

export const aiUsageMetrics = {
  tasksToday: 347,
  costThisMonth: 2847,
  mostActiveAgent: 'Lead Scout',
  tokensUsed: 1200000,
  tokensLimit: 2000000,
  tasksByDay: [
    { day: 'Mon', tasks: 42 },
    { day: 'Tue', tasks: 58 },
    { day: 'Wed', tasks: 35 },
    { day: 'Thu', tasks: 67 },
    { day: 'Fri', tasks: 51 },
    { day: 'Sat', tasks: 23 },
    { day: 'Sun', tasks: 18 },
  ],
}

// ─── Dashboard: Team Productivity ─────────────────────────────────────────

export const teamProductivity = {
  activeToday: 5,
  totalMembers: 7,
  tasksCompleted: 23,
  avgResponseTime: '1.2h',
  topPerformer: 'Sarah Chen',
  topPerformerTasks: 8,
  productivityByDay: [
    { day: 'Mon', completed: 18 },
    { day: 'Tue', completed: 22 },
    { day: 'Wed', completed: 15 },
    { day: 'Thu', completed: 28 },
    { day: 'Fri', completed: 23 },
    { day: 'Sat', completed: 10 },
    { day: 'Sun', completed: 7 },
  ],
}
